//: Playground - noun: a place where people can play

import UIKit

var str = "Hello, playground"

arc4random_uniform(1)
arc4random_uniform(5000)
arc4random_uniform(1)
arc4random_uniform(8)



print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
arc4random_uniform(200)
Thread.sleep(forTimeInterval: 0.01)
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))


print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
arc4random_uniform(200)
Thread.sleep(forTimeInterval: 0.01)
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))


print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
arc4random_uniform(200)
Thread.sleep(forTimeInterval: 0.01)
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))

print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
arc4random_uniform(200)
Thread.sleep(forTimeInterval: 0.01)
print((arc4random_uniform(500) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))
print((arc4random_uniform(2) + 2))